pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            SitFit
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://www.stair-rover.com/
#
# 2. URL of this page
url:              http://sitfit.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           Stair-Rover
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://kck.st/12bbLkw
  #
  # URL of a cover photo of your project
  cover_image:    http://dexterindustries.com/GrovePi/wp-content/uploads/2013/10/IMAG0735.jpg
  #
  # Use a one-liner to describe your project
  description:    SitFit is a healthy way to remember to stand up!
#
# 4. Your Twitter handle
twitter_handle:   StairRover
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  This is the Stair-Rover team greeting from London. <br />
  First of all, thank you for signing up to our mailing list. <br />
  Here's to tell you that our project is now live on Kickstarter,
  and now we have to count on your support to not only back the project, but also share the love. ♥
